services-all/pom.xml

Adding commons-text exclussion.

MULE-13034: Error responses with special characters should be scaped.

---

standalone/src/main/resources/bin/mule.bat

As customers use this parameter to check the status of mule running as service in Windows, it is a better option to use the Tanuki command.

MULE-12717: Add status parameter to mule.bat.

---

standalone/assembly-whitelist.txt
standalone/assembly.xml
standalone/src/main/resources/bin/mule
standalone/src/main/resources/bin/mule.bat

jcl-over-slf4j
Checking if a log level is enabled using the JUL api has different
processing times depending on the bridge used.
Benchmarking showed that jul-to-slf4j outperforms log4j-jul in a 1:10
ratio. Since this check using the jul api is used heavily by grizzly,
making this change should improve the performance of the http service.
Also, change the bridge of JCL for consistency. Benchmarking didn't show
any degradation

MULE-13968: Replace log4j-jul and log4j-jcl with jul-to-slf4j and

---

standalone/assembly-whitelist.txt

_ Upgrading log4j to 2.10.0
_ Upgrading disruptor to 3.3.7
_ Fixing test runner issue with context classloader

MULE-14070: Upgrade log4j to 2.9.1

---

standalone/assembly-whitelist.txt

* Upgrade transactions-api to 1.3
* Remove jaxen dependency

MULE-16042: javax packages not being resolved properly on JDK11

---

standalone/assembly-whitelist.txt

- Updating cglib to the latest version `3.2.10` which already supports ASM 7

MULE-15969: Upgrade cglib to latest version

---

standalone/assembly-whitelist.txt

- Updating whitelist after the changes on `mule-module-javaee` for
fixing test issues with Java 11 after the "JEP 320: Remove the Java EE
and CORBA Modules"

MULE-16417: Fix issues affecting mule-aggregators-module tests on Java 11

---

standalone/assembly-whitelist.txt

MULE-18383: Log4j upgrade on mule runtime 4.1.5, from log4j 2.11.0 to

---

bom/runtime-impl/pom.xml

- Bringing patches from `hfx-munit` branch to its support counterpart

DEL-149: Cherry-pick fixes of mule-distributions and mule-ee-distributions for Munit patches in new support patches of the released versions

---

Jenkinsfile
pom.xml

This is to avoid failing trying to resolve org.mule.runtime:api-annotations:jar:1.1.0-20200709
which only is available in private repos ci-releases and releases-ee

Remove maven settings with only public repos

---

standalone/src/main/resources/conf/wrapper.conf

(cherry picked from commit 67f192907220a0b452c5a8d75824ba3b52aaebac)

EE-7990: Warning Illegal reflective access by EfficientReflectionHashCode with JDK 11 when starting Runtime (#813)

---

embedded/embedded-distribution/pom.xml
standalone/assembly-allowlist.txt
standalone/pom.xml
standalone/src/assembly/assembly.xml

...effectively causing a split package error when starting up as module

W-12761115: `xml-apis` shadows classes already present in Java 11/17 `java.xml` module

---

standalone/assembly-allowlist.txt

In October of 2022, a [critical flaw](https://nvd.nist.gov/vuln/detail/CVE-2022-1471) was found in the SnakeYAML package, which allowed an attacker to benefit from remote code execution by sending malicious YAML content and this content being deserialized by the constructor. Finally, in February 2023, the SnakeYAML 2.0 release was pushed that resolves this flaw, also referred to as [CVE-2022-1471](https://nvd.nist.gov/vuln/detail/CVE-2022-1471). Let’s break down how this version can help you resolve this critical flaw.

W-12354025: Upgrade to snakeyaml 2.0 to address vulnerability in earlier versions

---

services-all/pom.xml
standalone/assembly-allowlist.txt

* Addendum: remove activation-api and leave just activation (ref: https://github.com/jakartaee/jaf-api/issues/18)

W-13588773: Replace all javax jars bundled in the runtime with the jakarta equivalent

---

standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf

This is just a cosmetic fix, because those numbers are actually overwritten by the [wrapper additional parameters parser](https://github.com/mulesoft/mule-distributions/blob/29a7e4b7a428fe448c0337b5b6401f9e3a099fd7/mule-wrapper-additional-parameters-parser/src/main/java/org/mule/runtime/params/AdditionalJvmParameters.java#L268).

W-12412013: Fixing sequence numbers for jvm-dependant wrapper additional parameters.

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/DefaultEmbeddedController.java
embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedController.java

* Force parsing of MUnit test configs, which are not included in the serialized AST for an application

W-13942158: "Missing element [munit:config] in file" when running MUnit tests with Runtime 4.5.0-rc10

---

embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/ApplicationTestCase.java

(cherry picked from commit 7c1644b66e54e1ee2853fd2ca83d7db89ebbd717)

W-13562329: don't run legacy implementation test with unsupported Java versions (#1131)

---

standalone/assembly-allowlist.txt

(cherry picked from commit ec64b3b496832c7fffd234b2ee494d0ee39b14a1)

W-14445662: Dotnet connector build in windows instance fails since guava upgrade in 4.4.0-20230724 (#1216)

---

standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf

(#1453) (#1454)
when an SQLException is thrown an it cannot be serialised

W-16546951: Batch job scope not executing second batch step with Java 17

---

standalone/src/main/resources/bin/mule.bat

[Cherrypick to 4.6] W-18056603: Remove trailing backslash on JAVA_HOME variable to prevent initialization error

---

standalone-structure/src/main/resources/README.txt

The links back to the developer documentation for the Mule Runtime have changed. Updating to the new URLs.

@W-16708214 Fixed links in readme
