mulesoft/mule-distributions

standalone/assembly-whitelist.txt
standalone/assembly.xml

depends on https://github.com/mulesoft/mule/pull/5359

MULE-11501: catalog manager support

---

standalone/assembly-whitelist.txt

MULE-13138: Decouple runtime and spring module from spring libraries

---

standalone/assembly-whitelist.txt
standalone/assembly.xml

depends on https://github.com/mulesoft/metadata-model-api/pull/90

MULE-13214: RAML type loader

---

embedded/embedded-test/src/main/java/org/mule/runtime/module/embedded/EmbeddedTestHelper.java
embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/ApplicationConfigurationTestCase.java
embedded/embedded-test/src/test/resources/failing/testapp/META-INF/maven/org.mule.test/testapp/pom.xml
embedded/embedded-test/src/test/resources/failing/testapp/META-INF/mule-artifact/mule-artifact.json
embedded/embedded-test/src/test/resources/failing/testapp/foo.xml
embedded/embedded-test/src/test/resources/failing/testapp/mule-config.xml
embedded/embedded-test/src/test/resources/successful/testapp/META-INF/maven/org.mule.test/testapp/pom.xml
embedded/embedded-test/src/test/resources/successful/testapp/META-INF/mule-artifact/mule-artifact.json
embedded/embedded-test/src/test/resources/successful/testapp/mule-config.xml

fixed tests for checking redeployment logic
formatter

MULE-13094 Embedded Container: If app fails to deploy, trying to deploy same app again ends instantly

---

standalone/assembly-whitelist.txt

_ Renaming api annotations artifact

MULE-14373 Define annotations to exclude java elements from the API

---

standalone/assembly-whitelist.txt

MULE-14675: Cannot destroy thread groups that have commons-pool evictor

---

standalone/src/main/resources/conf/log4j2.xml

MULE-14910: The Correlation Id in the MDC should not include format

---

standalone/src/main/resources/bin/launcher.conf

MULE-15092: Add launcher folder to groovy classpath so that WorkCloud can

---

services-all/pom.xml

* fix dependency, add implementation instead of api

MULE-15331: Upgrade javax.mail to javax.mail-api 1.6.2

---

embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/ApplicationTestCase.java
tests/src/test/java/org/mule/distributions/tests/AppControlTestCase.java

MULE-16470: Fix mule-distributions tests in Windows

---

standalone/assembly-whitelist.txt

MULE-16722: Update jaxb version to 2.3.1-MULE-001

---

standalone/src/main/resources/conf/log4j2.xml

MULE-18177: Add current location to thread names

---

tests/pom.xml

This reverts commit bbc12d2981ceb06965263adc1a3d4e41996c9654.

Revert "Add deployment notifier plugin dependency (#499)"

---

bom/runtime-api/pom.xml
standalone/assembly-whitelist.txt
standalone/assembly.xml

MULE-17199: Replace ApplicationModel instantiations with an ArtifactAST

---

embedded/embedded-test/src/test/resources/artifacts/apps/jdk-exported-resource-app/pom.xml

(cherry picked from commit 16d31c3597f0f30636d949ee7415ac7233039a37)

MULE-19224: Avoid forking the Java compiler (#606)

---

standalone/pom.xml

(cherry picked from commit 4a9709f65d69abf811e358c17f2a1da530fe6695)

MULE-19577: Upgrade log4j to 2.14.1 (#646)

---

standalone/assembly-whitelist.txt

(cherry picked from commit 23ee36ffe7ac0e91da8e5c6c4146d088c1c2bbdf)

MULE-19577: Upgrade log4j to 2.14.1 (#647)

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedController.java

(cherry picked from commit 734cfe88e368b67fc5cdbe57a74a0126f4a883df)

CMTS-238: Support SampleData for ToolingArtifact (#666)

---

embedded/embedded-test/pom.xml

(cherry picked from commit be76fa1914f569ccd25fb21b424c7ab4567715c9)

MULE-19615: Move third party dependencies in mule to runtime BOM (#656)

---

bom/runtime-api/pom.xml
pom.xml
services-all/pom.xml

(cherry picked from commit 72d1219f11364fe24b914d7d7e10a7ad29923f4e)

MULE-19745: Manage service versions in a BOM (#670)

---

standalone/assembly-allowlist.txt

(cherry picked from commit eb2b797c85617d4225849201d7ec22129b750194)

EE-8154: upgrade gson to 2.8.9 (#717)

---

standalone/assembly-allowlist.txt

Reverts mulesoft/mule-distributions#775

Revert "MULE-20018: Upgrade log4j dependency to 2.17.1/2.12.4"

---

standalone/assembly-allowlist.txt

(cherry picked from commit ce07ebdd4f41ce8bc4bccb49dd67fb8a51b39ea1)

W-10680271: Upgrade jackson version to 2.12.6 (#810)

---

standalone/assembly-allowlist.txt

(cherry picked from commit 325beab2b516edc588daec2a12cd87370fbf3bfa)

W-11139348: Upgrade jackson version to 2.13.3 (#844)

---

standalone/assembly-allowlist.txt

(cherry picked from commit b70d530e03e4a339923a87c0610f5c8d51b856ce)

W-11242363: Upgrade Tanuki wrapper to 3.5.50 (#871)

---

standalone/assembly-allowlist.txt

This reverts commit e121d2e2cb40b4845b38e3abc83e0da6aa7b49fc.

Revert "W-11242363: Upgrade Tanuki wrapper to 3.5.50 (#871) (#873)"

---

standalone/assembly-allowlist.txt

This reverts commit 3711598a2c21aa69dd94f3d4b7b7e740f9de2c60.

Revert "W-11242363: Upgrade Tanuki wrapper to 3.5.50 (#871) (#872)"

---

standalone/assembly-allowlist.txt

This reverts commit b70d530e03e4a339923a87c0610f5c8d51b856ce.

Revert "W-11242363: Upgrade Tanuki wrapper to 3.5.50 (#871)"

---

standalone/assembly-allowlist.txt

(cherry picked from commit bf310261f31b9331c0b7350d2c34f6be5305a378)

W-11741243: Upgrade SnakeYAML to 1.31

---

standalone/assembly-allowlist.txt

(cherry picked from commit 7e31bb701f0a25892524f3448fba831b47b227a1)

W-11834878: Upgrade json to version 20220924. (#909)

---

embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/EmbeddedLifecycleTestCase.java

W-11996026: Allow to query the embedded container version before

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedController.java
embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/impl/EmbeddedControllerDeploymentPropertiesTestCase.java

* Provide a way in embedded for the client code to create tooling objects

W-11742823: Review registry objects needed only by “fat” tooling

---

standalone/assembly-allowlist.txt

This reverts commit 4d6737756f3a9215fc6363d7d079e838a90a2ef3.

Revert "W-12219988: Upgrade log4j to version 2.19 (#941)"

---

standalone/assembly-allowlist.txt

(cherry picked from commit c132677f0b883a776fe81b5975ad74fd8039017b)

W-12219988: Upgrade log4j to version 2.19 (#947)

---

standalone/assembly-allowlist.txt

(cherry picked from commit 4d6737756f3a9215fc6363d7d079e838a90a2ef3)

W-12219988: Upgrade log4j to version 2.19 (#941)

---

standalone/src/main/resources/conf/wrapper.conf

(cherry picked from commit aaee8ae3dbf1e6cfb02429bd3645563eb562ec2a)

W-12549148: Enabling nashorn supported languages by default. (#970)

---

standalone/assembly-allowlist.txt

W-12305504: Upgrade byte-buddy version to make it compatible with Java

---

standalone/assembly-allowlist.txt

(cherry picked from commit 3f863425ca363c2d7193c71204c2a0234fb2a58d)

W-12680624: Upgrade `mule-classloader-model` version (#989)

---

standalone/assembly-allowlist.txt

remove shadowed class in mule-dsl-api

W-12741795: Add fix for MULE-19710/XERCESJ-1033 in our xerces fork and

---

standalone/assembly-allowlist.txt

(cherry picked from commit 7dda70dddfd5dfb279ea1c8a215a246988ec50ae)

W-13012142: Upgrade org.json:json to 20230227 (#1008)

---

mule-wrapper-additional-parameters-parser/src/test/resources/conf/wrapper.conf
standalone/assembly-allowlist.txt
standalone/src/assembly/assembly.xml
standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf
standalone/src/main/resources/conf/wrapper.conf

W-12740313: Allow usages of reflection (set accessible) in Scheduler

---

standalone/assembly-allowlist.txt

This is based on https://github.com/mulesoft/mule-distributions/pull/1029

W-12354025: Upgrade to snakeyaml 2.0 to address vulnerability in earlier versions

---

mule-wrapper-additional-parameters-parser/pom.xml

* Also, remove allure dependencies from root pom

W-13652525: Update allure version

---

standalone/src/main/resources/conf/wrapper.conf

W-12082402: Startup script gives higher priority to java in PATH instead of JAVA_HOME

---

standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf

* Add missing exports for standalone

W-13748730: Add module-info to mule-core and services apis

---

standalone/assembly-allowlist.txt

* Addendum: replace javax.inject also

W-13588773: Replace all javax jars bundled in the runtime with the jakarta equivalent

---

standalone/assembly-allowlist.txt

(cherry picked from commit 936f527d5ebed337944968ed3c56788b1ba8374d)

W-14081058: OTEL Java SDK upgrade.

---

standalone/assembly-allowlist.txt

(cherry picked from commit 26e0edb56c10a006f52f0900a93d9e9a1505b40d)

W-14077882: Handle concurrency with Maven provided features (#1159)

---

embedded/embedded-impl/pom.xml
embedded/embedded-impl/src/main/java/module-info.java
embedded/embedded-test/pom.xml
embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/AbstractEmbeddedTestCase.java
embedded/embedded-test/src/test/resources/artifacts/extensions/smart-connector-using-core/pom.xml

* Stabilize embedded-impl tests

W-13072016: Review JDKs used for building + running tests in Jenkins

---

tests/src/test/java/org/mule/distributions/tests/AppControlTestCase.java

W-14178331: Determine and set JAVA_HOME in launcher script it not

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedController.java

This reverts commit f426be36260a55d03c31cf7b42d06c4128b3d845.

W-13926363: Revert "fix Embedded Runtime not stopping (#1138)"

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/CommonsEmbeddedController.java

In #1178 we missed a spot due to a mistake during conflict resolution.

W-13967927: Adding missing chunk from previous revert.

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/CommonsEmbeddedController.java
embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/ApplicationTestCase.java

W-14445577: Fix hawk tests in Java 17

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/CommonsEmbeddedController.java
embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/ApplicationTestCase.java

W-14445577: Fix hawk tests in Java 17 (#1211)

---

standalone/assembly-allowlist.txt

W-14658834: Ensure all dependencies have their versions managed in the

---

embedded/embedded-test/pom.xml
tests/pom.xml

* Extract common release config
* Cleanup
* Address pending technical debt

W-15609911: Provide a common parent pom with pluginManangement of common

---

mule-wrapper-additional-parameters-parser/src/main/java/org/mule/runtime/params/AdditionalJvmParameters.java
mule-wrapper-additional-parameters-parser/src/test/java/org/mule/runtime/params/AdditionalJvmParametersTestCase.java
standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf

(cherry picked from commit ea42f7f16620511429e13014202b04a00f51df20)

W-15346051: fix startup failure on windows (#1344)

---

embedded/embedded-test/src/test/java/org/mule/runtime/module/embedded/AbstractEmbeddedTestCase.java

(cherry picked from commit 3c781a4e47c8d22497120bd83ba47ff8d13bb4cc)

W-15522743: fix `since` (#1345)

---

mule-wrapper-additional-parameters-parser/src/main/java/org/mule/runtime/params/AdditionalJvmParameters.java

(cherry picked from commit 006bbd0bbbe5873d88c2d52928dc6bf2143a35a4)

W-10618818: Support for jvmDependant options with two digits in the sequence number (#1362)

---

embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/CommonsEmbeddedController.java
embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/EmbeddedController.java
embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/IsolatedEmbeddedController.java
embedded/embedded-impl/src/main/java/org/mule/runtime/module/embedded/impl/util/FileUtils.java

(cherry picked from commit 00ccf89a26948fac08356a1b619e1e501023d92a)

W-15194080: Resolve Mule Runtime dependencies from local distro (#1373)

---

standalone/assembly-allowlist.txt

W-16541666: Update dependency plexus-component-annotations to v2.2.0

---

embedded/embedded-test/tests/pom.xml
embedded/embedded-test/tests/src/test/resources/artifacts/apps/pom-with-remote-repositories/META-INF/maven/test/pom-with-remote-repositories/pom.xml

* distro tests artifacts dependencies

W-16563701: Create a bom for test dependencies

---

standalone/src/main/resources/conf/java11-plus/wrapper.jvmDependant.conf

when an SQLException is thrown an it cannot be serialised

W-16546951: Batch job scope not executing second batch step with Java 17

---

standalone/assembly-allowlist.txt

W-16943447 fix icu4j version in assembly-allowlist

W-16943447 Update assembly-allowlist.txt

---

embedded/embedded-test/tests/pom.xml
embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/AbstractEmbeddedTestCase.java
embedded/embedded-test/tests/src/test/java/org/mule/runtime/module/embedded/ApplicationTestCase.java

without add-opens to ALL-UNNAMED

W-15810711: JDK17 - Support running MuleArtifactFunctionalTestCases

---

standalone/assembly-allowlist.txt

(cherry picked from commit c8e1239169f14045dea1936e7bda1b4a59d73b8a)

W-17896357: remove unused `jakarta.json`

---

standalone/assembly-allowlist.txt

Also cherry-picking:
- https://github.com/mulesoft/mule-distributions/pull/1504

W-17896357: remove unused `jakarta.json` (#1533)

---

standalone/assembly-allowlist.txt

Reverts mulesoft/mule-distributions#1526

Revert "W-18091023: Update jcommander to v2.0"
